networks:
  monitoring:
    driver: bridge

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - monitoring

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@audio_service-db-1:5432/postgres
    depends_on:
      - db
    ports:
      - 8000:8000
    networks:
      - monitoring

volumes:
  db_data: